spring:
  datasource: # 여러 DBaaS에서 가져오기
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver # PostgreSQL 드라이버 클래스 이름
  # 시큐리티
  security:
    user:
      name: ${SECURITY_NAME}
      password: ${SECURITY_PASSWORD}
# 로깅 설정
logging:
  level:
    org.example.bootsecurity.model.mapper: ERROR # mapper 패키지의 로깅 레벨을 ERROR 설정